### PR TITLE
SDK Fixes/Improvements & Continued Development of Demo App.

### PR DESCRIPTION
**Pull request by kikolobo**
Created the Develop branch, fixed a storyboard issue and a setter in setName for SparkDevice model class.

### CODE REVIEW

**Comment by kikolobo** [comment]
Started implementing a demo app for my own on the SDK current status.  

This request is for implementing the LoginViewController and basic login functionality from the main app.

##### NOTICE:

I don't know if this kind of additions (demo app) help you guy's or not... I am new to collaboration on GitHub but I am guessing that every little code helps sometimes.  Let me know if you want me to continue working on this or let it alone.

**Comment by towynlin** [comment]
Thanks @kikolobo! We love contributions of all kinds. You're awesome!

Check out spark.github.io for our contribution guidelines, and please sign the CLA here: https://docs.google.com/a/spark.io/forms/d/1_2P-vRKGUFg5bmpcKLHO_qNZWGi5HKYnfrrkd-sbZoA/viewform

**Comment by kikolobo** [comment]
Done signing

**Comment by kikolobo** [comment]
This pull request is to broad. I will make more focus pulls in the future. Sorry for that.

**Comment by idokleinman** [comment]
Is this still relevant?

**Comment by kikolobo** [comment]
Don't think so 😊 Too old.

**Comment by idokleinman** [comment]
Thanks!

**Pull request closed without merging**
