### PR TITLE
AFNetworking 3.0

### PR DESCRIPTION
**Pull request by mikekavouras**
Upgrade to AFNetworking 3.0. The majority of file changes are those in the library. The only functional change to the SDK is that each API method now returns an underlying `NSURLSessionDataTask` allowing for more flexibility (eg. canceling a task).

I've also added `osx_image:` to travis.yml which ensures a minimum language version.

### CODE REVIEW

**Comment by mikekavouras** [comment]
bump

**Comment by idokleinman** [comment]
Hey @mikekavouras, sorry I was in Xmas break till 4 days ago and came back to be swamped with non-iOS work.  Thanks so much for this contribution, this is super awesome! I promise to go over it/test and merge beginning of next week. Did you test it in any way?

**Comment by mikekavouras** [comment]
@idokleinman no problem. Just thought I'd give it a little nudge. Hope you had a good break :)

I'm using a forked version in a current project and everything is working as expected. That's the extent of my testing at the moment. I ran the suite and made sure CI passed.

https://github.com/mikekavouras/spark-sdk-ios
https://github.com/mikekavouras/Glowb-iOS

**Comment by idokleinman** [comment]
Hi Mike,
I've merged the PR into the SDK, thanks!
Two things:
1. I see that every SDK function now returns a NSURLSessionDataTask object, while in the past it returned nothing (void). What is the purpose of that and how would you explain it to the SDK users? What are they supposed to do with this object? I wish to keep abstracting the inner workings/comm of the library as much as possible.
2. The only SDK function that failed for me after the AFNetworking 3.0 migration is the flash files (`SparkDevice.m` line 405):
   `-(NSURLSessionDataTask *)flashFiles:(NSDictionary *)filesDict completion:(void (^)(NSError *))completion` 
   It is the only func to use a multipart form PUT request. Unfortunately the task never begins to execute. 
   Any insights?

Many thanks!

**Comment by mikekavouras** [comment]
Returning the underlying `NSURLSessionTask` allows for things like canceling the request or checking `state`. Very useful, especially for any situation where view reuse occurs, think `UICollectionView` or `UITableView`.

I can take a look at the second point. 

Thanks :)

**Comment by idokleinman** [comment]
Hi mike, did you take a look on the issue from your PR that `flashFiles` is not working with AFNetworking 3 (multipart PUT - task never starts)?

**Comment by mikekavouras** [comment]
@idokleinman not yet. Is there an easy way to test this?

**Pull request merged**
