### PR TITLE
Spec out nullability for Spark SDK

### PR DESCRIPTION
**Pull request by zackdotcomputer**
I was working on a little experimental app using the spark SDK and Swift and I kept running into problems where Swift's optional system would assume a value was nonnull when its nullability was actually important. Most notably were the error objects used in the completion callbacks. So, I went through the pod and spec'd out nullability on it. Hope this helps!

### CODE REVIEW

**Comment by idokleinman** [comment]
Thanks very much for this! We love contributions.
Did you have the chance to test it in a Obj-C and/or Swift projects?

**Comment by zackdotcomputer** [comment]
I tested it against the example objective-c project that was included in the pod (I wanted to make sure I didn't introduce warnings in the example project through the nullability checks). Honestly, I didn't expect a response in less than 24 hours so I hadn't had time to test against Swift yet. I was going to recompile the Swift 2 project I started on against this version later tonight. I will update with my results, though I don't expect to have any issues since I didn't change any of the public APIs of the pod other than through the nullability.

**Comment by idokleinman** [comment]
Excellent, keep me posted with results. Separately I'll test it against the full Particle app, if both our projects won't break I'll merge it in.

**Comment by zackdotcomputer** [comment]
I'm very interested to hear how it went with the Particle app. With my tiny test app it worked fine, though I also learned a couple things I might try to put into later pull requests. Out of curiosity, what iOS version are you targeting with the SDK?

**Comment by idokleinman** [comment]
now that AFNetworking 3 is in it should work fine on iOS 8+ methinks

**Pull request merged**
